baseURL = 'https://thhuang.dev'
languageCode = 'en-us'
title = 'TH Huang'
theme = 'nikki'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'github-dark'
    tabWidth = 4

[params]
author = 'TH Huang'
user = 'guest'
hostname = 'thhuang.dev'

[[params.social]]
key = 0
name = 'GitHub'
url = 'https://github.com/thhuang'

[[params.social]]
key = 1
name = 'LinkedIn'
url = 'https://www.linkedin.com/in/tzuhsuanhuang'

[[params.social]]
key = 2 
name = "Email"
url = "mailto:tzhsn.huang@gmail.com"
