baseURL: https://thhuang.dev
languageCode: en-us
title: TH Huang
theme: nikki
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: github-dark
    tabWidth: 4
params:
  author: TH Huang
  user: guest
  hostname: thhuang.dev
  social:
    - key: 0
      name: GitHub
      url: https://github.com/thhuang
    - key: 1
      name: LinkedIn
      url: https://www.linkedin.com/in/tzuhsuanhuang
    - key: 2
      name: Email
      url: mailto:tzhsn.huang@gmail.com
menu:
  header:
    - name: about
      url: /about
    - name: posts
      url: /posts
