# Page settings

baseURL = "https://thhuang.github.io/"
languageCode = "en"
title = "TH Huang"
theme = "hugo-devresume-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

[params]
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "TH Huang"
        tagline = "Backend Software Engineer"
        avatar = "avatar.jpg"

    [params.contact]
        enable = true
        location = "Taipei City, Taiwan"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+886 910095566"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "tzhsn.huang@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "thhuang.github.io"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Go"
        [[params.skills.list.items]]
        details = "Redis/Mongo/MySQL"
        [[params.skills.list.items]]
        details = "Dart/Flutter"
        [[params.skills.list.items]]
        details = "Docker"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MS in Computer-Aided Engineering"
        university = "National Taiwan University"
        dates = "2014 - 2016"
        [[params.education.list]]
        degree = "BS Civil Engineering"
        university = "National Taiwan University"
        dates = "2010 - 2014"

    [params.certifications]
        enable = true

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Mandarin Chinese"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Classical Music"
        [[params.interests.list]]
        name = "Reading"
        [[params.interests.list]]
        name = "App Development"

    [params.summary]
        enable = true
        text = "Software Engineer focusing on high QPS backend service design and development in Go/Golang. Amateur Flutter developer developing several cross-platform mobile applications. Experienced Robotics Software Engineer specializing in computer vision and the development of algorithms for autonomous drone control systems. Strong research professional with an M.S. degree of Computer-Aided Engineering from National Taiwan University."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Backend Software Engineer"
        dates = "2019 - Present"
        company = "17LIVIT"
        details = "Application Technology Team & On-Call Team"
        [[params.experience.list.items]]
        details = "Designed and implemented backend services to support new application features."
        [[params.experience.list.items]]
        details = "Developed internal tools and services for operation teams."
        [[params.experience.list.items]]
        details = "Daily deployment of the backend service."

        [[params.experience.list]]
        title = "Artificial Intelligence Researcher"
        dates = "2017 - 2019"
        company = "Taiwan AILabs"
        details = "Artificial Intelligence Drone Team & Computer Vision and Automatic Cinematography Team"
        [[params.experience.list.items]]
        details = "Implemented, and integrated algorithms into the ROS-based autonomous flight system. Modules include obstacle avoidance, motion planning, state estimation, LiDAR/visual SLAM, preflight verification, failsafe control."
        [[params.experience.list.items]]
        details = "Designed and developed 2 hardware prototypes of autonomous quadcopter and hexacopter."
        [[params.experience.list.items]]
        details = "Mentored three full-time interns to complete independent projects: Drone Hardware Development, SLAM, and Image Detection."
        [[params.experience.list.items]]
        details = "Developed a film shot detecting algorithm with unsupervised machine learning for automatic video editing."
        [[params.experience.list.items]]
        details = "Proposed a deep learning-based aesthetic view selecting algorithm for aerial 360° panoramic videos."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "NurMusik"
        meta = "Classical Music Radio App"
        tagline = "The best classical music radio app."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Classical Music, Reading"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/thhuang"
        title = "thhuang"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/tzuhsuanhuang"
        title = "tzuhsuanhuang"
