name: thhuang
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_background: ^1.0.5
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  fonts:
    - family: Oxanium
      fonts:
        - asset: assets/fonts/Oxanium/Oxanium-Regular.ttf
        - asset: assets/fonts/Oxanium/Oxanium-Medium.ttf
          weight: 500
    - family: AnonymousPro
      fonts:
        - asset: assets/fonts/AnonymousPro/AnonymousPro-Regular.ttf
