name = "Nikki"
license = "MIT"
licenselink = "https://github.com/thhuang/hugo-nikki/blob/master/LICENSE"
description = "Nikki the minimal dark theme for Hugo"
features = ["blog", "dark"]
min_version = "0.110.0"

[author]
name = "TH Huang"
homepage = "https://thhuang.dev"
